RESTApi/Api/Api/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('mainapp.authentication.urls')),
    path('api/', include('mainapp.userProfile.urls')),
    path('api/', include('mainapp.fileSystem.urls')),
    path('api/', include('mainapp.signCreation.urls')),
    path('api/', include(('mainapp.notifications.urls', 'web'), namespace='web')),
    path('api/', include('mainapp.signerWebSocket.urls')),
    path('api/Acutes/', include('djoser.urls.base')),
    # post ->/users/set_password/
    # get ->/users/ -> List of all the users -> permission isAdmin
]
# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

RESTApi/Api/mainapp/fileSystem/urls.py
from django.urls import path
from .views import (
    FileUploadView,
    FileDownloadView,
    LoadGrid,
    load_account_users,
    QuerysetConvert,
    GetSignedFile
    )

urlpatterns = [
    path('Acutes/Upload/', FileUploadView.as_view()),
    path('Acutes/Download/', FileDownloadView.as_view()),
    path('Acutes/ViewFile/', FileDownloadView.as_view()),
    path('Acutes/LoadGrid/', LoadGrid.as_view()),
    path('Acutes/LoadUserAccounts/', load_account_users.as_view()),
    path('Acutes/QueryAccountNames/', QuerysetConvert.as_view()), 
    path('Acutes/GetSignedFile/', GetSignedFile.as_view()), 
]

RESTApi/Api/mainapp/notifications/urls.py
from django.urls import path
from django.conf.urls import url

from .InvitingContributors.views import *
from .PasswordReset.views import *
from .index import NotificationView

urlpatterns = [
    path('Acutes/SendNotification/', NotificationView.as_view()),
    
    path('Acutes/Reset/<uidb64>/<token>/', PasswordResetConfirm, name="password_reset_confirm"),
    path('Acutes/Reset/password_reset_done/', PasswordResetDone, name='password_reset_done'),
    path('Acutes/Reset/password_reset_complete/', PasswordResetComplete, name='password_reset_complete'),

    path('Acutes/SendInvite/<uidb64>/<token>', ContributorConfirm, name="contributor_confirm"),

]

RESTApi/Api/mainapp/signCreation/urls.py
from django.urls import path
from .views import CreateSignView, DisplaySignView, EditSignView, DeleteSignView, GetSignView

urlpatterns = [
    path('Acutes/CreateSign/', CreateSignView.as_view(), name='CreateSignView'),
    path('Acutes/DisplaySign/', DisplaySignView.as_view(), name='DisplaySignView'),
    path('Acutes/EditSign/', EditSignView.as_view(), name='EditSignView'),
    path('Acutes/DeleteSign/', DeleteSignView.as_view(), name='DeleteSignView'),
    path('Acutes/GetSign/', GetSignView.as_view(), name='GetSignView'),
]

RESTApi/Api/mainapp/userProfile/urls.py
from django.urls import path
from .views import LoadProfileView, EditProfileView, ChangePasswordView, GetUserDetailView

urlpatterns = [
    path('Acutes/LoadProfile/', LoadProfileView.as_view(), name='LoadProfile'),
    path('Acutes/EditProfile/', EditProfileView.as_view(), name='EditProfile'),
    path('Acutes/ChangePassword/', ChangePasswordView.as_view(), name='ChangePassword'),
    path('Acutes/GetUserDetail/', GetUserDetailView.as_view(), name='GetUserDetailView'),
]

RESTApi/Api/mainapp/fileSystem/models.py
from django.db import models
from ..authentication.models import User, Account


def user_directory_path(instance, filename):
    if instance.IsSigned != True:
    #     return 'user_{0}/signed/{1}'.format(instance.User.id, filename)
    # else:
        return 'user_{0}/unsigned/{1}'.format(instance.User.id, filename)
    

class FilesModel(models.Model):
    User = models.ForeignKey(User,
                             default=1,
                             null=True,
                             on_delete=models.SET_NULL)
    Account = models.ForeignKey(Account, on_delete=models.CASCADE)

    File = models.FileField(upload_to = user_directory_path ,blank=False, null=False)

    # Filter Properties
    IsSigned = models.BooleanField(default=False)
    Date = models.DateField(auto_now_add=True, blank=True, null=False)
    DateTime = models.DateTimeField(auto_now_add=True)

RESTApi/Api/mainapp/models.py
from .authentication.models import Account, User, User_Account
from .fileSystem.models import FilesModel
from .signCreation.models import UserSign, UserSignText, UserSignImage

RESTApi/Api/mainapp/authentication/views.py
from django.db import transaction
from django.http import HttpResponse
from rest_framework.exceptions import ValidationError
# from rest_framework.throttling import UserRateThrottle
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import ensure_csrf_cookie, csrf_protect
from .serializers import (
    SignInSerializer,
    AccountSerializer,
    UserSerializer,
    UseAccSerializer
)
# from rest_framework.authentication import SafeJWTAuthentication
# from .authentication import SafeJWTAuthentication

from rest_framework.views import APIView
from rest_framework import status
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from rest_framework.decorators import api_view, permission_classes, authentication_classes
from ..utils.auth import (
    make_response,
    login_user,
    access_token_refresh
)

# from .prevent import UserLoginRateThrottle
from .models import User, User_Account, Account
from django.contrib.auth import get_user_model
from ..utils.notif import default_token_generator, decode

@authentication_classes([])
@permission_classes([])
class SignUpView(APIView):
    serializer_class1 = UserSerializer
    serializer_class2 = AccountSerializer
    serializer_class3 = UseAccSerializer
   
   
    def post(self, request, *args, **kwargs):

        # If the user is Invited and User is not signed up
        if request.query_params : 
            token = request.query_params['token']
            uid = request.query_params['uid']
            user, account_id = decode(uid)
            token_flag = default_token_generator.check_token(user, account_id, token)
            
            if token_flag and user and account_id:
                CreateAccount = False
                is_owner = False
                request.data['AccountName'] = Account.objects.get(pk = account_id).AccountName 
                request.data['EmailId'] = user
             
            else:
                return HttpResponse("ERROR 404 Invalid Credentials")
       
        else:
            CreateAccount = True
            is_owner = True
    
        user_found = False if not User.objects.filter(EmailId=request.data['EmailId']) else True
        is_owner = False

        # Opening a new account
        if CreateAccount:
            is_owner = True
            # To check if the account already exists. Raise Exception if it is present
            if Account.objects.filter(AccountName=request.data['AccountName']):
                raise Exception("This Account Already Exists")

            if not user_found:
                ser1 = self.serializer_class1(data=request.data)
                if ser1.is_valid():
                    with transaction.atomic():
                        ser1.save()
                else:
                    raise ValidationError("The User fields are invalid")

            ser2 = self.serializer_class2(data={'AccountName': request.data['AccountName']})
            if ser2.is_valid():
                with transaction.atomic():
                    ser2.save()
            else:
                raise ValidationError("The Account fields are invalid")

        # joining account but user doesn't exist
        elif not User.objects.filter(EmailId=request.data['EmailId']):
            ser1 = self.serializer_class1(data=request.data)

            if ser1.is_valid():
                with transaction.atomic():
                    ser1.save()
            else:
                raise ValidationError("The fields are invalid")

        
        user = User.objects.get(EmailId=request.data['EmailId'])
        if Account.objects.filter(AccountName=request.data['AccountName']):
            acc = Account.objects.get(AccountName=request.data['AccountName'])
        else:
            raise ValidationError("You cannot attach to this Account")

        
        ser3 = self.serializer_class3(data={'user': user.id, 'acc': acc.id, 'is_owner': is_owner})
        if ser3.is_valid():
            with transaction.atomic():
                ser3.save()

        return Response(status=status.HTTP_200_OK)


@authentication_classes([])
class SignInView(APIView):
    # throttle_classes = (UserLoginRateThrottle,)
    serializer_class = SignInSerializer
    permission_classes = [AllowAny]

    @method_decorator(ensure_csrf_cookie)
    def post(self, request):
        
        data = request.data
        serializer = self.serializer_class(
            data=data,
            context={"request": request}
        )

        if not serializer.is_valid():
            first_errors = {k: v[0] for k, v in serializer.errors.items()}
            return make_response(False, first_errors)

        user = serializer.save()
        tokenvals = login_user(request, user)
        response = Response()
        response.set_cookie(key='refreshtoken', value=tokenvals['refresh_token'], httponly=True, )
        response.set_cookie(key="accesstoken", value=tokenvals['access_token'], httponly=True, )
        # response.set_cookie(key="id", value=user.id)
        response.data = {
            'access_token': tokenvals['access_token'],
            'id': user.id,  # store it inside sessionStorage
            'EmailId': user.EmailId  # store it inside sessionStorage or LocalStorage

        }

        return response
        # return Response(status=status.HTTP_200_OK)

 
@api_view(['POST'])
@permission_classes([AllowAny])
@authentication_classes([])  
@csrf_protect
def token_refresh(request):
    data = access_token_refresh(request)
    response = Response()
    response.set_cookie(key="accesstoken", value=data['access_token'], httponly=True, )
    response.data = data
    return response


class SignOutView(APIView):
    permission_classes = [AllowAny]
    authentication_classes = []

    @method_decorator(csrf_protect)
    def post(self, request):

        response = Response()

        if request.COOKIES.get('refreshtoken'):
            response.delete_cookie('refreshtoken')

        if request.COOKIES.get('accesstoken'):
            response.delete_cookie('accesstoken')

        if request.COOKIES.get('csrftoken'):
            response.delete_cookie('csrftoken')

        if request.COOKIES.get('sessionid'):
            response.delete_cookie('sessionid')

        return response


class GetUserAccounts(APIView):
    permission_classes = [AllowAny]
    authentication_classes = []

    def post(self, request):
        if User.objects.filter(EmailId=request.data['EmailId']):
            user = User.objects.get(EmailId=request.data['EmailId'])
        else:
            return Response("User doesn't exist", status=status.HTTP_400_BAD_REQUEST)
        user_accounts = User_Account.objects.filter(user=user.id)
        user_accounts = list(user_accounts)
        val = []
        for user_account in user_accounts:
            val.append({'Account' :user_account.acc.AccountName})

        response = Response()
        response.data = {
            'result': val
        }
        return response

RESTApi/Api/mainapp/notifications/InvitingContributors/views.py
from django.shortcuts import redirect
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes , force_text
from django.db import transaction
from django.core.mail import EmailMessage
from django.conf import settings
from django.urls import reverse
from urllib.parse import urlencode

from rest_framework.decorators import api_view, authentication_classes, permission_classes, renderer_classes
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework import status
from rest_framework.renderers import JSONRenderer, TemplateHTMLRenderer
from rest_framework.views import APIView

from ...utils.notif import default_token_generator, account_activation_token, decode
from ...authentication.serializers import UseAccSerializer
from ...authentication.models import User, Account, User_Account

# from ..index import SendMail
from ...tasks import SendMail


@api_view(['GET'])
@permission_classes([AllowAny])
@authentication_classes([])
def ContributorConfirm(request, uidb64 , token):
    ctx = {}
    if request.method == 'GET':
        try:
            user, account = decode(uidb64)

        except(TypeError, ValueError, OverflowError):
            user = None

        if user is not None and account is not None and default_token_generator.check_token(user, account, token):
            
            # If user exists already then he will just be joined
            
            if User.objects.filter(EmailId=user):
            
                user = User.objects.get(EmailId=user)
                
                if not User_Account.objects.filter(acc = account).filter(user=user.id):    
                    ser3 = UseAccSerializer(data={'user': user.id, 'acc': account, 'is_owner': False})
                    if ser3.is_valid():
                        with transaction.atomic():
                            ser3.save()
                    # Return to a "Thank You For joining" Template  
                    ctx = {"message": "Thank you for joining"}
                    return render(request, 'Inval_Thank.html', ctx) 

                else :
                    # return HttpResponse("User is already joined")
                    return redirect('/api/Acutes/SignIn/')

            
            # If he doesn't exist then he will be redirected to the signup page with fields off
            else: 
                base_url = reverse('SignUp')
                query_string = urlencode({'uid':uidb64, 'token':token})
                url = '{}?{}'.format(base_url, query_string)
                return redirect(url)
            

        else:
            ctx = {"message": "This link has expired/invalid"}
            return render(request, 'Inval_Thank.html', ctx)

  
#  Testing Zone #

def InviteContributorss(email, dic_bod, current_site):

    dic = {}
    account = Account.objects.filter(AccountName = dic_bod['Account'])
    users = dic_bod['Users_Invited'] # will be a list of users
    sender = email   
    
    sender_name = User.objects.get(EmailId=sender).FullName

    if account :
        account = account[0]
        from_email = settings.EMAIL_HOST_USER
        
        template = '2WYS_Invitation_Mail.html'
        
        for user in users:
            dic ={   
                    'subject': "Invitation to contribute",
                    'message': "Inviting all the contributors",
                    'domain' : current_site.domain,
                    'uid' : urlsafe_base64_encode(force_bytes("EmailId:"+str(user)+"<#>account:"+str(account.pk))),
                    'token': default_token_generator.make_token(account.pk, user),
                    'account': account.AccountName,
                    'FullName': sender_name,
                    'Sender': sender,
                    'attach_filename': None
                }
            print(current_site.domain)
            # SendMail(from_email, [user], dic, template)
        # SendMail.delay(from_email, to_list, dic, template)

RESTApi/Api/mainapp/notifications/ShareFiles/views.py
import json
import os
import zipfile
from ...authentication.models import User
from ...fileSystem.models import FilesModel
from rest_framework.permissions import AllowAny
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, serializers
from ...tasks import SendMail
from django.conf import settings
from ...utils.files import create_zip, check_dir_path

@authentication_classes([])
@permission_classes([AllowAny])
def ShareFiles(email, dict_bod):

    # dic_bod will contain list of file ids
    users = dict_bod['Users_Invited'] # will be a list of users
    sender = email
    queryset = dict_bod['FileIds']
    from_email = settings.EMAIL_HOST_USER
    file_path = ""

    if len(queryset) > 1:
        check_dir_path('media', 'zipfiles')
        # push it into utils
        zip_filename = create_zip(queryset, False, "2WYS_Attachment", None)
        file_path = zip_filename

    else:
        fid = queryset[0]
        fname = FilesModel.objects.get(pk=str(fid)).File
        file_path = 'media/'+ str(fname)
        
    for user in users:
        template = 'ShareFiles.html'
        dic ={
                'subject': "Sharing Files",
                'message': "Here are the files shared with you",
                'account': None,
                'sender': sender,
                'attach_filename': file_path
            }
        SendMail(from_email, [user], dic, template)

RESTApi/Api/mainapp/templates/BaseLogin.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
  <title>Login</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>

  <style>
/*       
    .box{
      background: url({% static "/img/21-login.jpg" %});
      background-size: cover;
      background-position: center;
      height: 100vh;
      box-shadow: inset 0px 0px 100px black;
    } */
    .contenido
    {
      background-color: transparent;
      height: 55vh;
      border-radius: 10px;

      box-shadow: 0px 0px 60px black;
    }

  </style>
  <body>

  <header>
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
        <div><a class="navbar-brand" href="/api/Acutes/SignIn/">Click here to go back</a></div>
      </nav>
  </header>


{% block content_login %}
  
{% endblock content_login %}


    <script src="{%static 'js/jquery.js' %}"></script>
    <script src="{%static 'js/tether/dist/js/tether.min.js' %}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
  </body>
</html>

RESTApi/Api/mainapp/templates/BasePassword.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Reset Password</title> 
    <!-- Required meta tags -->
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
</head>

  <style>
    .contenido
    {
      background-color: transparent;
      height: 55vh;
      border-radius: 10px;

      box-shadow: 0px 0px 60px black;
    }

    .emsg{
        color: red;
    }
    .hidden {
         visibility:hidden;
    }


  </style>
  <body>

    <nav class="navbar navbar-toggleable-md navbar-light bg-faded navbar-inverse bg-inverse"> 
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
              <a class="nav-link" href="/api/Acutes/SignIn/"> Home <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
    </nav>

{% block content_password %}
  
{% endblock content_password %}


    <script src="{% static 'js/jquery.js' %}"></script>
    <script src= "{%static 'js/tether/dist/js/tether.min.js' %}" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
 
    <script type="text/javascript" src= "{% static 'js/regularExpresions.js' %}"></script>

  </body>
</html>

RESTApi/Api/mainapp/templates/EmailBodySent.html
Please do not reply to this message.
Click on the given link to reset password for {{user.get_username}} 


{% block reset_link %}
http://{{ domain }}{% url 'web:password_reset_confirm' uidb64=uid  token=token%}
{% endblock reset_link %}

RESTApi/Api/mainapp/templates/Inval_Thank.html
{% extends "BasePassword.html" %}

{% block content_password %}
<section class="container-fluid">
    <div class="row justify-content-center box">
      <div class="col-sm-8 col-md-6 col-lg-5 align-self-center contenido">
        <div class="row justify-content-center" style="height: 55vh;">
          <div class="col-sm-12 col-md-12 col-lg-10 align-self-center">
            <center>
               <div>
                    <div class="form-group">
                    <h3 style="color:black;">{{message}}</h3>
                    <button type="button" style="background-color: #3a906d; color:white;" class="btn btn-primary colorbtn" onclick="location.href='/api/Acutes/SignIn/';">Return to sign in</button>
                    </div>
                </div>
            </center>
          </div>
        </div>
      </div>
    </div>
</section>
	

{% endblock content_password %}
<!--/api/Acutes/SignIn/-->

RESTApi/Api/mainapp/templates/PasswordMailSent.html
{% extends "BaseLogin.html" %}
{% load static %}

{% block content_login %}

 <section class="container-fluid">
    <div class="row justify-content-center box">
      <div class="col-sm-8 col-md-6 col-lg-5 align-self-center contenido">
        <div class="row justify-content-center" style="height: 55vh;">
          <div class="col-sm-12 col-md-12 col-lg-10 align-self-center">
              <center>
                  <h3 style="color:black;">We have sent you an email to change your password</h3>
                  <button type="button" style="background-color: #3a906d; border-width:0px;" class="btn btn-primary" onclick="location.href='/api/Acutes/SignIn/';">Click to SignIn</button>
              </center>
          </div>
        </div>
      </div>
    </div>
</section>
	
{% endblock content_login %}

RESTApi/Api/mainapp/templates/PasswordReset.html
{% extends "BasePassword.html" %}


{% block content_password %}
	  <section class="container-fluid">
    <div class="row justify-content-center box">
      <div class="col-sm-8 col-md-6 col-lg-5 align-self-center contenido">
        <div class="row justify-content-center" style="height: 55vh;">
          <div class="col-sm-12 col-md-12 col-lg-10 align-self-center">
            <center>
               <div>
                <h3 style="color:white;">Change your Password</h3> 
                {% if message.0 %}
                    Please Try again 
                {% else %}         
                  Welcome {{ user }}
                {% endif %}
                <br>
              </div>
              <form method="POST"> {% csrf_token %}
                <div class="form-group">
                <input type="password" name="password1" placeholder="Enter Password" class="PASS"><br><br>
                <input type="password" name="password2" placeholder="Enter Password Again">
                </div><span class="emsg hidden" id="pass">It is recommended to have a strong password with more than 10 characters</span><br>
            
                <button type="submit" style="background-color: #3a906d; color:white;" class="btn btn-primary" >Submit</button><br>
                {% if message.0 %}
                    <h3 style="color:black;">{{message}}</h3>
                {% endif %}
              </form>
            </center>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content_password %}

RESTApi/Api/mainapp/templates/ResetComplete.html
{% extends "BasePassword.html" %}
{% load static %}

{% block content_password %}<section class="container-fluid">
    <div class="row justify-content-center box">
      <div class="col-sm-8 col-md-6 col-lg-5 align-self-center contenido">
        <div class="row justify-content-center" style="height: 55vh;">
          <div class="col-sm-12 col-md-12 col-lg-10 align-self-center">
            <center>
                <div class="form-group">
                <h3 style="color:white;">The Password has been reset</h3> 
                <button type="button" style="background-color: #3a906d; color:white;" class="btn btn-primary colorbtn" onclick="location.href='/api/Acutes/SignIn/';">Click to SignIn</button>
                </div>
            </center>
          </div>
        </div>
      </div>
    </div>
  </section>
	
	
{% endblock content_password %}

RESTApi/Api/mainapp/templates/ShareFiles.html
Please do not reply to this message.

The files have been shared to you by {{sender}}
PFA